### PR TITLE
WIP: Support Calico

### PR DESCRIPTION
**Pull request by niusmallnan**
For compatibility with Calico
Pls see https://github.com/rancher/rancher/issues/8603#issuecomment-297648946

### CODE REVIEW

**Comment by leodotcloud** [comment]
The logic of passing the `IP` from the label `io.rancher.container.ip` for CNI glue looks good.

Things to consider:
- The IP address for the container might not be available at the time of invocation of the CNI plugin. So the label might be empty.
- I don't know if on cattle side this label `io.rancher.container.ip` is set for all IPAM plugins. If that's the case, say a user requested to use calico-ipam but cattle ignored it and set the label then we would end up in a conflicting situation. Hence we should have a check in cattle to not allocate IP address and not set this label if the user decides to use calico-ipam instead of rancher-ipam.

**Comment by cjellick** [comment]
@leodotcloud I dont follow this. Can you explain further?
> The IP address for the container might not be available at the time of invocation of the CNI plugin. So the label might be empty.

because as far as I know, by the time the container is created, we are guaranteed to have the IP from cattle.

RE:
> I don't know if on cattle side this label...

If when configuring the network_service section of the rancher-compose for calico, you omit subnet, that will tell cattle that it should not be the IPAM provider. In that case, `io.rancher.container.ip` will not be present. *But note:* we don't have any real plugins that do this. Calico would be the first. Which means, bugs are likley.

**Comment by leodotcloud** [comment]
@cjellick I am speaking from my experience looking at the rancher-cni-ipam logs, the IP address was not available immediately all the times. But IPAM plugin reads from metadata. So may be the label can have the IP 100% of the time but propagating to metadata might take time?

**Comment by cjellick** [comment]
Yes @leodotcloud, that's accurate: label will be 100% correct. Metadata is less predictable due to propagation delay

**Pull request closed without merging**
